## template: jinja
#cloud-config

# SET OUR VARIABLES
# =================

# Choose which channel of self-hosted Landscape you wish to deploy: stable|beta|edge
{% set CHANNEL = 'edge' %}

# Ubuntu Pro token (leave blank for Ubuntu Pro instances on Azure, AWS, or Google Cloud)
{% set TOKEN = '' %}

# Assuming you use SSL from LetsEncrypt, follow these steps on your Ubuntu workstation
# replace landscape.yourdomain.com with the domain name you will use for Landscape

# sudo snap install certbot --classic
# sudo certbot -d landscape.yourdomain.com --manual --preferred-challenges dns certonly

# The value for SSL_CERT below is the output of:
# sudo base64 -w 0 /etc/letsencrypt/live/landscape.yourdomain.com/fullchain.pem
{% set SSL_CERT = 'SELFSIGNED' %}

# The value for SSL_KEY below is the output of:
# sudo base64 -w 0 /etc/letsencrypt/live/landscape.yourdomain.com/privkey.pem
{% set SSL_KEY = 'SELFSIGNED' %}

# =========================
# END OF SETTING VARIABLES

packages:
  - iptables
  - iptables-persistent
  - snapd
  - ubuntu-advantage-tools
package_update: true
package_upgrade: true
package_reboot_if_required: true

snap:
 commands:
   - ['install', 'juju', '--classic']
   - ['install', 'jq']

runcmd:
{% if platform == 'gce' %}
 - lxd init --auto
 - su ubuntu -c 'lxc network set lxdbr0 bridge.mtu=1460'
{% endif %}
{% if platform == 'oracle' %}
 - iptables -F && netfilter-persistent save
{% endif %}
 - su ubuntu -c 'juju bootstrap localhost lxdlandscape'
 - su ubuntu -c "juju set-model-constraints arch=$(dpkg --print-architecture)"
 - su ubuntu -c "juju deploy landscape-scalable --channel {{ CHANNEL }}"
 - |
   if [ $(dpkg --print-architecture) = 'arm64' ]; then
     /bin/bash /tmp/redeploy_haproxy.sh
   else
{% if SSL_KEY != "SELFSIGNED" %}
     su ubuntu -c "juju config haproxy ssl_cert='{{ SSL_CERT }}' ssl_key='{{ SSL_KEY }}'"
{% endif %}
     /bin/bash /home/ubuntu/iptables_portforward.sh
   fi
 - /bin/bash /tmp/juju_containers_active_check.sh

write_files:
  - path: /tmp/redeploy_haproxy.sh
    owner: 'ubuntu:ubuntu'
    permissions: '0755'
    defer: true
    content: |
      #!/bin/bash
      echo "$(date +'%Y-%m-%d %H:%M:%S'): redeploy_haproxy.sh started - arm64 detected, HAProxy charm needs to be redeployed on arm64 architectures"
      su ubuntu -c 'juju remove-application haproxy'
      su ubuntu -c "juju deploy haproxy --config default_timeouts='queue 60000, connect 5000, client 120000, server 120000' --config services='' --config ssl_cert='{{ SSL_CERT }}' --config ssl_key='{{ SSL_KEY }}' --config global_default_bind_options='no-tlsv10' --series focal"
      su ubuntu -c 'juju expose haproxy'
      su ubuntu -c 'juju relate landscape-server haproxy'
      echo "$(date +'%Y-%m-%d %H:%M:%S'): redeploy_haproxy.sh completed"
      /bin/bash /home/ubuntu/iptables_portforward.sh
  - path: /home/ubuntu/iptables_portforward.sh
    owner: 'ubuntu:ubuntu'
    permissions: '0755'
    defer: true
    content: |
      #!/bin/bash
      echo "$(date +'%Y-%m-%d %H:%M:%S'): iptables_portforward.sh started - waiting for all containers to be assigned an IP"
      iptables -t nat -L --line-numbers | grep 'haproxy' | awk -F '' '{print $1}' | sort -rn | xargs -I {} iptables -t nat -D PREROUTING {}
      read -r HAPROXY_INSTANCE_NUMBER < <(su - ubuntu -c "juju status --format=json | awk -F'haproxy/' '{print substr(\$2,1,1)}'")
      while true; do
        address=$(su ubuntu -c "juju status --format=json | jq -r --arg INSTANCE haproxy/$HAPROXY_INSTANCE_NUMBER '.applications[\"haproxy\"].units[$INSTANCE][\"public-address\"]'")
        if [ "$address" != "null" ]; then
          echo "$(date +'%Y-%m-%d %H:%M:%S'): haproxy/$HAPROXY_INSTANCE_NUMBER has an IPv4 Address: $address, finalizing network setup"
          break
        fi
        echo "$(date +'%Y-%m-%d %H:%M:%S'): haproxy/$HAPROXY_INSTANCE_NUMBER has no IPv4 address yet, waiting..."
        sleep 5
      done
      read -r HAPROXY_UNIT_IP < <(su ubuntu -c "juju run --unit haproxy/$HAPROXY_INSTANCE_NUMBER 'network-get public --ingress-address=true'")
      read -r INTERFACE INTERFACE_IP < <(ip -4 route ls | awk '/default/{print $5, $9}')
      for PORT in 443 80; do
        iptables -t nat -I PREROUTING -i $INTERFACE -p tcp -d $INTERFACE_IP --dport $PORT -j DNAT --to-destination $HAPROXY_UNIT_IP:$PORT -m comment --comment haproxy
      done
      echo "$(date +'%Y-%m-%d %H:%M:%S'): iptables_portforward.sh completed"
  - path: /tmp/juju_containers_active_check.sh
    owner: 'ubuntu:ubuntu'
    permissions: '0755'
    defer: true
    content: |
      #!/bin/bash
      while true; do
        countA=$(su ubuntu -c "juju status --format json | grep -o '\"application-status\":' | wc -l")
        countB=$(su ubuntu -c "juju status --format json | grep -o '\"application-status\":{\"current\":\"active\"' | wc -l")
        if [ $countA -eq $countB ]; then
          echo "$(date +'%Y-%m-%d %H:%M:%S'): All Juju containers are in an active state"
          break
        else
          echo "$(date +'%Y-%m-%d %H:%M:%S'): Waiting for all containers to be in an active state"
          sleep 10
          su ubuntu -c "juju status"
        fi
      done

ubuntu_advantage:
{% if TOKEN %}
  token: {{ TOKEN }}
{% endif %}
  enable:
  - livepatch